# -*- coding: utf-8 -*-
"""Tentativa 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c-AmoeTyEzxtKjSgQyDZRe6p16IAUBwP
"""

# Quantos numeros o usuario quer usar
quantidade = int(input("Quantos numeros você quer usar?: "))

# Resultado da soma!
resultado = None

# Sumário de operação
print("Escolha sua operação")
print("digite 1 para somar")
print("digite 2 para multiplicação")
print('digite 3 para módulo/resto da divisão')
print('digite 4 para subtração')

# Escolha da operação
operacao = int(input("escolha sua operação: "))

for i in range(quantidade):
  numero = float(input(f"Digite o número {i+1}: "))
  if resultado is None:
    resultado = numero
  else:
        if operacao == 1:
            resultado += numero
        elif operacao == 2:
            resultado *= numero
        elif operacao == 3:
            resultado %= numero
        elif operacao == 4:
            resultado -= numero

# Mostrando o resultado final.
if operacao == 1:
    print(f'o total da soma é: {resultado} ')
elif operacao == 2:
        print(f'o total da multiplicação é: {resultado} ')
elif operacao == 3:
        print(f'o total do módulo/resto da divisão é: {resultado} ')
elif operacao == 4:
        print(f'o total da subtração é: {resultado}')
else:
        print('Nenhuma operação válida! Tente com uma das escolhas do sumário!')